before:
  hooks:
    - go mod tidy
builds:
  - id: sesmtpd
    main: ./cmd/sesmtpd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
#      - windows
#      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
#      - 6
      - 7
  - id: sendmail
    main: ./cmd/sendmail
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    #      - windows
    #      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
#      - 6
      - 7
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
